---
- hosts: all
  become: yes
  become_user: root
  tasks:
          - name: Change Hostname
            hostname:
                    name: "demo-ops"
          
          - name: Create a user "demo"
            user:
                    name: demo
                    shell: /bin/bash
                    
          - sysctl:
                  name: vm.swappiness
                  value: '5'
                  state: present

          - sysctl:
                  name: net.ipv4.ip_forward
                  value: '1'
                  sysctl_set: yes
                  state: present
                  reload: yes

          - sysctl:
                  name: fs.file-max
                  value: 2097152

          - sysctl:
                  name: net.core.somaxconn
                  value: 65535
                  
          - name: Set Timezone to Asia/Kolkata
            timezone:
                    name: Asia/Kolkata

          - name: Install Docker
            apt: name=docker

          - name: Install Docker Compose
            apt: name=docker-compose

          - name: Deploying docker-compose
            docker_compose:
                    project_src: /home/vagrant/go-app/
            register: output

          

