version: '3'
services:
        redis:
                image: redis
                volumes:
                        - ../data/redis:/data
                ports:
                        -  "6379:6379"
                
        app:
                 build:
                         context: .
                         dockerfile: Dockerfile
                 links: 
                        - redis
                 depends_on:
                         - redis
                 ports:
                         - "8080:8080"
 
